log_level: TRACE # TRACE WARNING

task:
    eda_mode: False  # True False

experiment:
    model: mobilenet
    name: ${experiment.model}

paths:
    roots:
        # /home/stud/ath/ath_ws/others/traffic_sign_recognition
        # D:/code/traffic_sign_recognition
        project: /home/stud/ath/ath_ws/others/traffic_sign_recognition
        data: ${paths.roots.project}/data
        output: ${paths.roots.project}/output

    output:
        logs: ${paths.roots.output}/logs
        checkpoints: ${paths.roots.output}/checkpoints

image:
    image_size: 224

train:
    batch_size: 64

    fast_dev_run: False  # True False
    overfit_batches: 0

    patience: 3
    max_epochs: 100
    check_val_every_n_epoch: 3
    num_sanity_val_steps: 1
    log_every_n_steps: 1
    accumulate_grad_batches: 1
    learning_rate: 1e-4

val:
    batch_size: 64

test:
    batch_size: 64

loggers:
    #  - tensorboard
   - neptune
